---
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319
      grpc:
        endpoint: 0.0.0.0:4320
processors:
  batch:
    timeout: 1s
  resource:
    attributes:
      - key: test.key
        value: gateway
        action: insert
  tail_sampling:
    decision_wait: 2s
    num_traces: 100
    expected_new_traces_per_sec: 1
    policies: []
exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    send_timestamps: true
    namespace: promexample
    const_labels:
      label1: value1
  logging:
    loglevel: info
  otlp/aspecto:
    endpoint: otelcol.aspecto.io:4317
    headers:
  otlp/honeycomb:
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: 0FfNYwQPNTGW6meRFuKGtI
      X-Honeycomb-Team: 1
      X-Honeycomb-Writekey: 1
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true
  elasticsearch/trace:
    endpoints: [http://elastic:9200]
    tls:
      insecure: true
extensions:
  health_check: null
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
service:
  extensions:
    - pprof
    - zpages
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
        - resource
      exporters:
        - logging
        - otlp/aspecto
        - otlp/jaeger
        - elasticsearch/trace
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - prometheus



    
    
